project_id = "pwysjzyhhyfxhbymmklz"

[functions.generate-image]
verify_jwt = false

[functions.schedule-processor]
verify_jwt = false

[functions.generate-multi-image]
verify_jwt = false

[functions.print-on-shirt-processor-correct]
verify_jwt = false

[functions.process-completed-predictions]
verify_jwt = false

[functions.journal-blog-post]
verify_jwt = false