project_id = "sphgdlqoabzsyhtyopim"

[api]
enabled = true
port = 54321

[db]
enabled = true
port = 54322

[functions.generate-image]
verify_jwt = false

[functions.schedule-processor]
verify_jwt = false

[auth]
enabled = true
port = 54324