project_id = "sphgdlqoabzsyhtyopim"

[functions.generate-image]
verify_jwt = false

[functions.schedule-processor]
verify_jwt = false

[functions.generate-multi-image]
verify_jwt = false

[functions.print-on-shirt-processor]
verify_jwt = false

[functions.process-print-on-shirt]
verify_jwt = false

[functions.test-replicate-no-auth]
verify_jwt = false