// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sphgdlqoabzsyhtyopim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwaGdkbHFvYWJ6c3lodHlvcGltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODc3MjEsImV4cCI6MjA2NjQ2MzcyMX0.uXtmbccpR_lZ-lywL1qogPmAePFRb8YnUkuAAv35Q5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});